# Site settings
title: Pebbles
email: pebblesgames@gmail.com
description: "Game blog for Pebbles, an indie game development studio based out of Ontario, Canada."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pebblesgames.com" # the base hostname & protocol for your site
twitter_username: PebblesGames
github_username:  alexpennells

# Build settings
markdown: kramdown
