# Site settings
title: Alex Pennells
email: pennellsa@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexpennells.com" # the base hostname & protocol for your site
twitter_username: Dank3yKang
facebook_url: "https://www.facebook.com/alex.pennells"
linkedin_url: "https://ca.linkedin.com/pub/alex-pennells/44/a88/50a"
github_username:  alexpennells
resume_url: "https://drive.google.com/file/d/0B0Q80tzEuWWFWjhPTG1lNUdaQ28/view?usp=sharing"

# Build settings
markdown: kramdown
